import Hero from "../components/Hero";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sunnyside</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>

      <main className="">
        <Hero />
      </main>
    </div>
  );
}
